### ISSUE TITLE
README / how to run

### ISSUE THREAD

**Issue by FelixAgner** [max65945/mpcofdhg_ecc24#1]
I was very excited to see someone working on district heating in Julia :) However, I'm not sure how to run it or where to start fiddling with it. Could you create a minimal readme with e.g. a short usage guide, a link to the paper and license info?

**Comment by max65945** [comment]
You should be able to run the [src/mpcofdhg_ecc24.jl](https://github.com/max65945/mpcofdhg_ecc24/blob/main/src/mpcofdhg_ecc24.jl) which then runs the simulation. 
You can also see the order of execution of the scripts in [src/mpcofdhg_ecc24.jl](https://github.com/max65945/mpcofdhg_ecc24/blob/main/src/mpcofdhg_ecc24.jl), which can be helpful for changing some simulation details yourself.
Of course this doesn't replace a README, we will work on it :)

**Comment by FelixAgner** [comment]
Great, thank you :)

I'd say that your comment there is basically good enough to make a minimalistic README ;)
